---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf-deployment
spec:
  selector:
    matchLabels:
      app: nginx-sf

  replicas: 3

  template:
    metadata:
      labels:
        app: nginx-sf

    spec:
      containers:
      - name: nginx-sf-container
        image: nginx:1.21.1-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx/"
          readOnly: true

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-sf
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }


